<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1552044319557" stop="1552044319591">
  <name>scripts.test_login</name>
  <labels/>
  <test-cases>
    <test-case start="1552044319557" status="passed" stop="1552044319559">
      <name>TestLogin.test_login01</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="28708-MainThread"/>
        <label name="host" value="DESKTOP-5GVIRKP"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1552044319560" status="failed" stop="1552044319591">
      <name>TestLogin.test_login02</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;scripts.test_login.TestLogin object at 0x00000215DF9696A0&gt;

    def test_login02(self):
&gt;       assert 0
E       assert 0

scripts\test_login.py:6: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="28708-MainThread"/>
        <label name="host" value="DESKTOP-5GVIRKP"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
